---
version: '3.6'

services:

  web:
    build:
      context: ./
      dockerfile: Dockerfile-ngix
    image: baqend/webpagetest-nginx:2021-06-24
    ports:
      - "80:8080"
    volumes:
      - /var/www/webpagetest/www/results:/var/www/webpagetest/results:ro
    deploy:
      replicas: 1
      placement:
        constraints:
          - 'node.labels.master == true'

  php:
    build:
      context: ./
      dockerfile: Dockerfile-php
    image: baqend/webpagetest-php:2021-06-24
    volumes:
      - /var/www/webpagetest/www/results:/var/www/webpagetest/results
    deploy:
      replicas: 1
      placement:
        constraints:
          - 'node.labels.master == true'
    secrets:
      - source: wpt_settings_ini
        target: /var/www/webpagetest/settings/settings.ini
      - source: wpt_keys_ini
        target: /var/www/webpagetest/settings/keys.ini

networks:
  default:

secrets:
  wpt-key:
    external: true
  wpt_settings_ini:
    external: true
  wpt_keys_ini:
    external: true

volumes:
  wpt-results:
